import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#f5f6f8" },
  content: { padding: 20, paddingBottom: 40 },
  header: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderBottomColor: "#e7e9ee",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 16,
  },
  headerButton: { height: 28, justifyContent: "center", width: 28 },
  headerTitle: { color: "#0e2038", fontSize: 18, fontWeight: "800" },
  kicker: {
    color: "#b8975a",
    fontSize: 11,
    fontWeight: "800",
    textAlign: "right",
  },
  title: {
    color: "#0e2038",
    fontSize: 28,
    fontWeight: "800",
    marginTop: 7,
    textAlign: "right",
  },
  subtitle: {
    color: "#7c879b",
    fontSize: 13,
    marginTop: 5,
    textAlign: "right",
  },
  titleRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 7,
  },
  titleCopy: { flex: 1 },
  panel: {
    backgroundColor: "#fff",
    borderColor: "#e7e9ee",
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 18,
    padding: 16,
  },
  row: {
    alignItems: "center",
    borderBottomColor: "#eef0f2",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 10,
    paddingVertical: 14,
  },
  rowCopy: { flex: 1 },
  rowTitle: {
    color: "#0e2038",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "right",
  },
  rowMeta: { color: "#7c879b", fontSize: 12, marginTop: 4, textAlign: "right" },
  badge: {
    backgroundColor: "#f5eee1",
    borderRadius: 8,
    color: "#9a7841",
    fontSize: 11,
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  action: {
    alignItems: "center",
    backgroundColor: "#0e2038",
    borderRadius: 10,
    flexDirection: "row",
    gap: 7,
    justifyContent: "center",
    marginTop: 16,
    padding: 14,
  },
  actionText: { color: "#fff", fontSize: 13, fontWeight: "700" },
  input: {
    borderColor: "#dfe3e8",
    borderRadius: 9,
    borderWidth: 1,
    color: "#0e2038",
    fontSize: 14,
    marginTop: 7,
    padding: 12,
    textAlign: "right",
  },
  compactInput: {
    backgroundColor: "#fff",
    borderColor: "#dfe3e8",
    borderRadius: 8,
    borderWidth: 1,
    color: "#0e2038",
    fontSize: 13,
    marginTop: 5,
    minHeight: 40,
    paddingHorizontal: 10,
    paddingVertical: 8,
    textAlign: "right",
  },
  textArea: { minHeight: 84, textAlignVertical: "top" },
  dateInput: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderColor: "#dfe3e8",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "flex-end",
    marginTop: 5,
    minHeight: 40,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  dateInputText: {
    color: "#0e2038",
    flex: 1,
    fontSize: 13,
    textAlign: "right",
  },
  dateInputPlaceholder: {
    color: "#526071",
  },
  linkedCaseActions: {
    flexDirection: "row",
    gap: 8,
    marginTop: 7,
  },
  caseActionButton: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderColor: "#dfe3e8",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 42,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  caseActionButtonActive: {
    backgroundColor: "#f5efe5",
    borderColor: "#b8975a",
  },
  caseActionButtonText: {
    color: "#526071",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  caseActionButtonTextActive: {
    color: "#0e2038",
  },
  radioGroup: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 7,
  },
  radioBtn: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderColor: "#dfe3e8",
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: "center",
    minWidth: "30%",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  radioBtnActive: {
    backgroundColor: "#f5efe5",
    borderColor: "#b8975a",
  },
  radioBtnText: {
    color: "#526071",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  radioBtnTextActive: {
    color: "#0e2038",
  },
  casePickerOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(14,32,56,0.45)",
    bottom: 0,
    justifyContent: "center",
    left: 0,
    padding: 24,
    position: "absolute",
    right: 0,
    top: 0,
  },
  casePickerSheet: {
    backgroundColor: "#fff",
    borderRadius: 16,
    maxHeight: "75%",
    width: "100%",
  },
  casePickerTitle: {
    color: "#0e2038",
    fontSize: 18,
    fontWeight: "800",
    paddingHorizontal: 18,
    paddingTop: 18,
    textAlign: "right",
  },
  casePickerContent: {
    padding: 18,
    paddingTop: 8,
  },
  casePickerItem: {
    backgroundColor: "#f8fafc",
    borderColor: "#e5e7eb",
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  casePickerItemActive: {
    backgroundColor: "#f5efe5",
    borderColor: "#b8975a",
  },
  casePickerItemText: {
    color: "#0e2038",
    fontSize: 14,
    fontWeight: "600",
    textAlign: "right",
  },
  casePickerItemTextActive: {
    color: "#0e2038",
  },
  pickerWrapper: {
    backgroundColor: "#fff",
    borderColor: "#dfe3e8",
    borderRadius: 9,
    borderWidth: 1,
    marginTop: 7,
    overflow: "hidden",
  },
  picker: { color: "#0e2038", height: 42 },
  modalBackdrop: {
    backgroundColor: "rgba(14,32,56,0.35)",
    flex: 1,
    justifyContent: "flex-end",
  },
  modalKeyboardContainer: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: "78%",
    overflow: "hidden",
    width: "100%",
  },
  modalContent: { padding: 18, paddingBottom: 12 },
  modalTitle: {
    color: "#0e2038",
    fontSize: 20,
    fontWeight: "800",
    textAlign: "right",
  },
  modalAction: {
    alignItems: "center",
    backgroundColor: "#0e2038",
    borderRadius: 9,
    justifyContent: "center",
    marginTop: 14,
    padding: 11,
  },
  deleteAction: {
    alignItems: "center",
    backgroundColor: "#fee2e2",
    borderRadius: 9,
    justifyContent: "center",
    marginTop: 14,
    padding: 11,
  },
  deleteActionText: {
    color: "#b91c1c",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  modalCancel: {
    color: "#526071",
    fontSize: 13,
    paddingTop: 10,
    textAlign: "center",
  },
  label: {
    color: "#526071",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 14,
    textAlign: "right",
  },
  empty: { color: "#7c879b", padding: 30, textAlign: "center" },
  danger: { color: "#c0503f", fontSize: 12, fontWeight: "700" },
  memberAvatar: {
    alignItems: "center",
    backgroundColor: "#e7f0fa",
    borderRadius: 10,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  avatarText: { color: "#3b6fa0", fontSize: 13, fontWeight: "800" },
  segment: {
    alignItems: "center",
    backgroundColor: "#f3f4f6",
    borderRadius: 8,
    flex: 1,
    padding: 10,
  },
  segmentActive: { backgroundColor: "#b8975a" },
  segmentText: { color: "#526071", fontSize: 11, fontWeight: "700" },
  segmentTextActive: { color: "#fff" },
  segments: { flexDirection: "row", gap: 7, marginTop: 16 },
  stat: {
    backgroundColor: "#fff",
    borderColor: "#e7e9ee",
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    padding: 12,
  },
  statLabel: { color: "#7c879b", fontSize: 11, textAlign: "right" },
  statValue: {
    color: "#0e2038",
    fontSize: 22,
    fontWeight: "800",
    marginTop: 4,
    textAlign: "right",
  },
  stats: { flexDirection: "row", gap: 8, marginTop: 18 },
});
