import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#f5f6f8" },
  content: { padding: 20, paddingBottom: 40 },
  header: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderBottomColor: "#e7e9ee",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 16,
  },
  headerButton: { height: 28, justifyContent: "center", width: 28 },
  headerTitle: { color: "#0e2038", fontSize: 18, fontWeight: "800" },
  kicker: {
    color: "#b8975a",
    fontSize: 11,
    fontWeight: "800",
    textAlign: "right",
  },
  title: {
    color: "#0e2038",
    fontSize: 28,
    fontWeight: "800",
    marginTop: 7,
    textAlign: "right",
  },
  subtitle: {
    color: "#7c879b",
    fontSize: 13,
    marginTop: 5,
    textAlign: "right",
  },
  titleRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 7,
  },
  titleCopy: { flex: 1 },
  panel: {
    backgroundColor: "#fff",
    borderColor: "#e7e9ee",
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 18,
    padding: 16,
  },
  row: {
    alignItems: "center",
    borderBottomColor: "#eef0f2",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 10,
    paddingVertical: 14,
  },
  rowCopy: { flex: 1 },
  rowTitle: {
    color: "#0e2038",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "right",
  },
  rowMeta: { color: "#7c879b", fontSize: 12, marginTop: 4, textAlign: "right" },
  badge: {
    backgroundColor: "#f5eee1",
    borderRadius: 8,
    color: "#9a7841",
    fontSize: 11,
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  action: {
    alignItems: "center",
    backgroundColor: "#0e2038",
    borderRadius: 10,
    flexDirection: "row",
    gap: 7,
    justifyContent: "center",
    marginTop: 16,
    padding: 14,
  },
  actionText: { color: "#fff", fontSize: 13, fontWeight: "700" },
  input: {
    borderColor: "#dfe3e8",
    borderRadius: 9,
    borderWidth: 1,
    color: "#0e2038",
    fontSize: 14,
    marginTop: 7,
    padding: 12,
    textAlign: "right",
  },
  label: {
    color: "#526071",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 14,
    textAlign: "right",
  },
  empty: { color: "#7c879b", padding: 30, textAlign: "center" },
  danger: { color: "#c0503f", fontSize: 12, fontWeight: "700" },
  memberAvatar: {
    alignItems: "center",
    backgroundColor: "#e7f0fa",
    borderRadius: 10,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  avatarText: { color: "#3b6fa0", fontSize: 13, fontWeight: "800" },
  segment: {
    alignItems: "center",
    backgroundColor: "#f3f4f6",
    borderRadius: 8,
    flex: 1,
    padding: 10,
  },
  segmentActive: { backgroundColor: "#b8975a" },
  segmentText: { color: "#526071", fontSize: 11, fontWeight: "700" },
  segmentTextActive: { color: "#fff" },
  segments: { flexDirection: "row", gap: 7, marginTop: 16 },
  stat: {
    backgroundColor: "#fff",
    borderColor: "#e7e9ee",
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    padding: 12,
  },
  statLabel: { color: "#7c879b", fontSize: 11, textAlign: "right" },
  statValue: {
    color: "#0e2038",
    fontSize: 22,
    fontWeight: "800",
    marginTop: 4,
    textAlign: "right",
  },
  stats: { flexDirection: "row", gap: 8, marginTop: 18 },
});
